//
// Generated file, do not edit! Created by nedtool 5.6 from Packet_m.msg.
//

#ifndef __PACKET_M_M_H
#define __PACKET_M_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>Packet_m.msg:21</tt> by nedtool.
 * <pre>
 * //
 * // Represents a packet in the network.
 * //
 * packet Packet
 * {
 *     int srcAddr;
 *     int destAddr; // also contain neighbour in Hello msgs
 *     int hopCount; // also give number of transient nodes 
 *     simtime_t travelTime;
 *     int transientNodes[]; //std::vector<int> transientNodes; size gives hops in path for BA
 * }
 * </pre>
 */
class Packet : public ::omnetpp::cPacket
{
  protected:
    int srcAddr;
    int destAddr;
    int hopCount;
    ::omnetpp::simtime_t travelTime;
    int *transientNodes; // array ptr
    unsigned int transientNodes_arraysize;

  private:
    void copy(const Packet& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Packet&);

  public:
    Packet(const char *name=nullptr, short kind=0);
    Packet(const Packet& other);
    virtual ~Packet();
    Packet& operator=(const Packet& other);
    virtual Packet *dup() const override {return new Packet(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSrcAddr() const;
    virtual void setSrcAddr(int srcAddr);
    virtual int getDestAddr() const;
    virtual void setDestAddr(int destAddr);
    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
    virtual ::omnetpp::simtime_t getTravelTime() const;
    virtual void setTravelTime(::omnetpp::simtime_t travelTime);
    virtual void setTransientNodesArraySize(unsigned int size);
    virtual unsigned int getTransientNodesArraySize() const;
    virtual int getTransientNodes(unsigned int k) const;
    virtual void setTransientNodes(unsigned int k, int transientNodes);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Packet& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Packet& obj) {obj.parsimUnpack(b);}


#endif // ifndef __PACKET_M_M_H

